version : '3.8'

volumes:
  postgres_data:
  static:

services:
  postgres_db:
    container_name: phystech-job-postgres-db
    build:
      context: ./postgres_db
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      DB_HOST: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  backend_app:
    build:
      context: ./backend_app
    container_name: phystech-job-backend-app
    volumes:
      - ./backend_app/:/app/
      - static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  frontend_app:
    build:
      context: ./frontend_app
    container_name: phystech-job-frontend-app
    depends_on:
      - backend_app
    ports:
      - "8080:8080"
    volumes:
      - ./frontend_app:/app
      - ./frontend_app/node_modules:/app/node_modules

  nginx:
    build:
      context: ./nginx
    container_name: phystech-job-nginx
    networks:
      static-network:
        ipv4_address: 195.161.68.20
    depends_on:
      - backend_app
    ports:
      - "80:7000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/static